name: torchSCF CI
run-name: ${{ github.actor }} running (conda) build-test workflow

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-conda-run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Build env & run tests
        run: |
          conda env create -f environment.yml

          conda init bash
          source ~/.bashrc
          eval "$(conda shell.bash hook)"

          conda activate th_scf
      
          pytest ./tests/