name: torchSCF CI
run-name: ${{ github.actor }} running (conda) build-test workflow

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  ruff-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Run ruff
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv add ruff 
          uv run ruff check .

  build-uv-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Build with uv and run tests
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync 
          uv run pytest